### ISSUE TITLE
Add a new section of Completed Programs in the Readme

### ISSUE THREAD

**Issue by Hackerbone** [eldhoittangeorge/pythonicway#22]
It would be nice to see a table of completed programs and who completed them.
Easier for new contributors to see what all programs have been completed.

If you find this feature good , then do assign this issue to me @eldhoittangeorge

**Comment by eldhoittangeorge** [comment]
That's a good idea. I will do it today. Thanks 👍

**Comment by Hackerbone** [comment]
@eldhoittangeorge can I do this? pls assign it to me and add label as hacktoberfest!

**Comment by eldhoittangeorge** [comment]
Please proceed
